--- 
- name: Provision Instance
  hosts: all
  become: yes
  tasks:  
      - name: update OS
        become: yes
        yum:
          name=*
          state=latest

      - name: install wget curl nmap vim net-tools
        yum:
          skip_broken: yes
          name:
          - wget
          - curl
          - nmap
          - curl
          - vim 
          - net-tools
          - htop
          - letsencrypt
          state:
            present

      - name: change hostname
        hostname:
            name: "{{ server_host_name }}"

    

              


