--- 
- name: Provision Instance
  hosts: all
  become: yes
  tasks:  
      - name: update OS
        become: yes
        yum:
          name=*
          state=latest

      - name: install wget curl nmap vim net-tools
        yum:
          skip_broken: yes
          name:
          - wget
          - curl
          - nmap
          - curl
          - vim 
          - net-tools
          state:
            present

      - name: change host name
        become: yes
        shell: |
          hostnamectl set-hostname "{{ server_host_name }}"

    

              


