--- 

- name: Test
  hosts: webservers
  tasks:
    - name: who am I again
      shell: |
         whoami;
         /usr/bin/uptime
      register: result

    - name: print debug message        
      debug:
        var: result
        verbosity: 2


       