---

- hosts: webservers
  user: root
  tasks:
  - name: ensure wget present
    yum: name=wget state=present

  - name: download virtualmin install script
    shell: wget http://software.virtualmin.com/gpl/scripts/install.sh creates=/root/install.sh

  - name: virtualmin install executable
    file: path=/root/install.sh mode=0755
    
  - name: virtualmin install (possibly ~15 mins)
    shell: ~/install.sh --yes chdir=/root

  - name: Virtualmin Post-Installation Wizard
    pause: prompt="virtualmin post-installation, https://{{inventory_hostname}}:10000"